import {
  Sparkles,
  Home,
  BarChart2,
  BarChart3,
  PenLine,
  MessagesSquare,
  Newspaper,
  CreditCard,
  Store,
  Bell,
  Users,
  LifeBuoy,
  TrendingUp,
  ShoppingBag,
  Receipt,
  Calendar,
  Image as ImageIcon,
  Settings,
  Wallet,
  Rocket,
  Flower2,
  Smartphone,
  PanelBottom,
  HelpCircle,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  home: Home,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'pen-line': PenLine,
  'messages-square': MessagesSquare,
  newspaper: Newspaper,
  'credit-card': CreditCard,
  store: Store,
  bell: Bell,
  users: Users,
  'life-buoy': LifeBuoy,
  'trending-up': TrendingUp,
  'shopping-bag': ShoppingBag,
  receipt: Receipt,
  calendar: Calendar,
  image: ImageIcon,
  settings: Settings,
  wallet: Wallet,
  rocket: Rocket,
  flower: Flower2,
  smartphone: Smartphone,
  'panel-bottom': PanelBottom,
};

export function getGuideIcon(key: string): LucideIcon {
  return ICON_MAP[key] ?? HelpCircle;
}
